[project]
name = "drivex-server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.7",
    "djangorestframework>=3.15.2",
    "djangorestframework-simplejwt[crypto]>=5.5.0",
]
